language: cpp

compiler:
  - gcc
  - clang

cache: apt

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DWITH_GMP=true -DBUILD_TESTING=ON -DWARNING_AS_ERROR=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug  -DWITH_MAGICK=true -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON"

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libgmp-dev libqglviewer-qt4-dev libinsighttoolkit3-dev libgdcm2-dev

##libboost-thread-dev  libeigen3-dev liblapack-dev libblas-dev libmpfr-dev
##CGAL specific (WIP)
#  - mkdir cgal && cd cgal
#  - wget https://gforge.inria.fr/frs/download.php/32994/CGAL-4.3.tar.gz
#  - tar zxvf CGAL-4.3.tar.gz && cd CGAL-4.3
#  - cmake . -DWITH_Eigen3=true -DWITH_GMPXX=true -DWITH_LAPACK=true -DWITH_BLAS=true
#  - make -s
#  - sudo make install -s
#  - cd ../..


matrix:
  exclude:
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug  -DWITH_MAGICK=true -DBUILD_TESTING=ON"
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON"
    - compiler: gcc
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON"
    - compiler: clang
      env: BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON"


script:
  - cmake . $BTYPE
  - make DGtal
  - make DGtalIO
  - cd examples
  - make
  - cd ../tests
  - make
  - cd ..
  - make
  - make test
