language: cpp

compiler:
  - gcc
  - clang

cache: apt

notifications:
  slack: dgtal:FObxCZFoeQkkaRuktJD5uhnN

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_MAGICK=true -DWITH_GMP=true  -DBUILD_TESTING=ON  -DWARNING_AS_ERROR=ON -DWITH_COVERAGE=true"
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_CAIRO=true -DWITH_QGLVIEWER=true -DBUILD_TESTING=ON -DWARNING_AS_ERROR=OFF"

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost-program-options-dev libcairo2-dev libgraphicsmagick++1-dev libboost-system-dev libgmp-dev libqglviewer-qt4-dev libinsighttoolkit3-dev libgdcm2-dev
  - gem install coveralls-lcov
  - sudo apt-get install -y lcov

script:
  - cmake . $BTYPE
  - make DGtal && make DGtalIO
  - cd examples && make -j 3 
  - cd ../tests &&  make &&  cd ..&& make test
  - tests/geometry/surfaces/testTensorVoting

after_script:
  - make lcov
  - coveralls-lcov --source-encoding=ISO-8859-1 coverage/stap.info
